apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-{{ .Values.name }}
  labels:
    name: pv-nfs-{{ .Values.name }}
spec:
  capacity:
    storage: {{ .Values.storage }}
  accessModes:
    {{ toYaml .Values.accessModes | indent 1 }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    {{ toYaml .Values.mountOptions | indent 1 }}
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: "{{ .Values.server }}##{{ .Values.share }}"
    volumeAttributes:
      server: {{ .Values.server }}
      share: {{ .Values.share }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-{{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: nfs-csi
  selector:
    matchLabels:
      name: pv-nfs-{{ .Values.name }}
  accessModes:
    {{ toYaml .Values.accessModes | indent 1 }}
  resources:
    requests:
      storage: {{ .Values.storage }}